### ISSUE TITLE
Obsolete unneeded duplicates of CHEBI classes

### ISSUE THREAD

**Issue by StroemPhi** [nmrML/nmrCV#15]
- [ ] [NMRCV:chemical compound](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000881) should be obsoleted and be replaced by [CHEBI:molecular entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_23367), as already suggested in its comment. 
- [ ] The same goes for its children [NMRCV:molecule](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000859), [NMRCV:peptide](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000860) and [NMRCV:protein](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000882), which have the CHEBI equivalents: [CHEBI:molecule](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_25367), [CHEBI:peptide](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_16670) and [CHEBI:protein](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_36080).

----
related to: #4 & #9

**Comment by NRayya** [comment]
The second task was discussed and the terms were considered irrelevant for nmrCV at this point. Better to remove them until deemed necessary.
