### ISSUE TITLE
Importing CHEBI dependencies

### ISSUE THREAD

**Issue by StroemPhi** [nmrML/nmrCV#6]
We need to add these NMR solvents: https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:197449&treeView=true#vizualisation
and these chemicla shif refernece compounds https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:228364 from CHEBI

**Comment by NRayya** [comment]
So far, nmrCV is only a taxonomy including only is_a relationship. However, has_role that comes from CHEBI makes more sense when it comes to the imported solvents here.

**Comment by StroemPhi** [comment]
I propose the following, which I do in the [CHEBI import branch](https://github.com/nmrML/nmrCV/tree/Import-CHEBI-dependencies)

1. Import all molecular entities from CHEBI that are asserted to have an [NMR solvent](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_197449) role --> done in 5e560edf7a3f251aaaf976877be923e589e6e5a3
2. Move [CHEBI:chemical entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_24431) under [BFO:material entity](https://terminology.nfdi4chem.de/ts/ontologies/bfo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040). It could also be subsumed under BFO:object, but this avoids the object/object aggregate distinction problem (see also: https://pubmed.ncbi.nlm.nih.gov/21533043) --> done in 530fd10fbcfffef07c7c62546dbdba931aac8a2f
3. Change the label of CHEBI:`NMR solvent` to `NMR solvent role` as it is defined as a role and not the material entity that bears this role --> done in 4c6f9bff707a55c41fc827706efc115007d9a733. Consider adding a comment which explains this label change.
4. Move [NMR solvent](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000330) under [CHEBI:molecular entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_23367), because all NMR solvents are molecular entities, and add an equivalenceTo axiom that states that an NMR solvent is a molecular entity that bears the CHEBI:NMR solvent role. --> done in bd96327781098503fb6947b127f019edf1829861
5. Add the textual definition to NMR solvent: "A molecular entity that is used as a solvent in nuclear magnetic resonance (NMR) spectroscopy." --> done in 35d403ce778592fdcb79820e35b0c2a0f5d61657
6. Infer subclassOf NMR solvent axioms for those CHEBI molecular entities which bear a CHEBI:NMR solvent role using: `sh run.sh robot reason --reasoner ELK -i nmrcv-edit.owl --exclude-duplicate-axioms true --exclude-tautologies structural --annotate-inferred-axioms True convert -f ofn -o nmrcv-edit.owl`. This will be done automatically upon building the actual release files, but must be done manually, if we want to see this also in the edit file. --> done in dbde30f1d3f7b0a5808476389f0118d2157b5a36
7. Obsolete heavy water in favor of imported CHEBI equivalent --> done in 6dcf40bb653015ba81e07e1ca22cdde0d271736e
8. Obsolete Hexafluorobenzene in favour of imported CHEBI equivalent. Currently needs us to assert that `CHEBI:38589 (hexafluorobenzene) 'has role' some 'NMR solvent role'` as this is currently not asserted in CHEBI --> done in 28df8f441be19460f06723501e5387f0fff2a3c3 & 79e9d84c039d0168d02f1ce8b0cb39c50141cf50
9. Request adding `CHEBI:38589 (hexafluorobenzene) 'has role' some 'NMR solvent'` upstream in CHEBI, so we can drop this axiom from our edit file in the future --> will be done by @NRayya 
10. Obsolete Chloroform-d in favor of imported CHEBI equivalent --> done in c963fa783e0f39e14d3641cba76998751b96587c

**Comment by StroemPhi** [comment]
Regarding Chemical shift reference compound, I propose the following, which I do in the [CHEBI import branch](https://github.com/nmrML/nmrCV/tree/Import-CHEBI-dependencies):

1. Import all molecular entities from CHEBI that are asserted to have an [NMR chemical shift reference compound](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_228364) role --> done in 000670234b01d87395ebe72ca91b98fe99a48ae6 & f318d8c661953d2817826e1e06bbb4b4f83ae829
2. Move [NMRCV:calibration compound](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400032) under [CHEBI:molecular entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_23367) --> done in b95e94d022031498829006abad59e63bb3271937
3. Add an equivalenceTo axiom that states that an [NMRCV:chemical shift standard](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400033) is a calibration compound that bears the [NMR chemical shift reference compound](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_228364) role. --> done in a8fd02f762a5eb944281f423dcf22879178955d0
4. Add general class axiom `'molecular entity' and ('has role' some 'NMR chemical shift reference compound') SubClassOf 'chemical shift standard'`, which is needed to infer CHEBI entities that are chemical shift reference compounds (defining new parent role for calibration compound would be also possible, but probably harder to get into CHEBI ) --> done in 90c24b67e556bf18bfce2e0b621392860be6b9ea
5. Infer subclassOf 'chemical shift standard' axioms for those CHEBI molecular entities which bear a CHEBI:'NMR chemical shift reference compound' role using: `sh run.sh robot reason --reasoner ELK -i nmrcv-edit.owl --exclude-duplicate-axioms true --exclude-tautologies structural --annotate-inferred-axioms True convert -f ofn -o nmrcv-edit.owl`. This will be done automatically upon building the actual release files, but must be done manually, if we want to see this also in the edit file. --> done in 90c24b67e556bf18bfce2e0b621392860be6b9ea

**Comment by NRayya** [comment]
I requested the addition of NMR solvent role to hexafluorobenzene https://github.com/ebi-chebi/ChEBI/issues/4487
