### ISSUE TITLE
New term: characterized compound 

### ISSUE THREAD

**Issue by NRayya** [nmrML/nmrCV#9]
## Preferred term label

characterized compound 

## Textual definition

A compound characterized in an NMR sample using data acquired from an NMR analysis

## Suggested parent term

molecular entity

**Comment by NRayya** [comment]
I have added the subclass "characterized compound" to the class molecular entity from CHEBI dd95f026c06680a19cd65d58b278bf1931e9dd04 with the provided definition.

**Comment by NRayya** [comment]
As we are not going to add any children to the term, it might be better to provide it as a role instead.

**Comment by StroemPhi** [comment]
Yes @NRayya, defining it as a role makes more sense.

**Comment by NRayya** [comment]
- [ ] add term characterized compound as child to molecular entity
- [ ] def: A molecular entity characterized in an NMR sample using data acquired from an NMR analysis
- [ ] Add role characterized compound as child to  chemical role
- [ ] def: the role of molecular entity being characterized in an NMR sample using data acquired from an NMR analysis
